### ISSUE TITLE
[Quest]工具太大占用显示空间

### ISSUE THREAD

**Issue by junjian-yuan** [liyunfan1223/unbot-addon#3]
非常感谢开发这个工具，很好用！

请问这个工具能增加缩放功能吗？
在笔记本屏幕下，将UI缩放设置到最小，这个工具显示还是很大，特别的占显示空间。
或者能自动收缩到一个图标中，点击图标在完整的显示。

谢谢！

**Comment by liyunfan1223** [comment]
谢谢，我觉得确实需要。但是我对插件开发不太熟悉，目前这个项目是从其他插件简单修改之后移植过来的，短时间内我自己可能加不了这个功能

**Comment by shenk-co** [comment]
非常好用，哈哈。
目前用下来只有重置机器人天赋的命令不起作用，每次使用总是提示没用选定目标，可否查看一下

**Comment by MRafStudio** [comment]
嗯，我认为这是一个单独的请求。 因此，这一特定的问题可以关闭。

**Comment by MRafStudio** [comment]
Well, I think this is a separate request. And therefore this particular one could be closed.
